version: '3'

services:
  gitea:
    image: gitea/gitea
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "${HTTPS_PORT:-443}:443"
      - "${SSH_PORT:-22}:22"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  infra_runner:
    image: gitea/act_runner
    restart: on-failure
    depends_on:
      - gitea
    environment:
      - GITEA_INSTANCE_URL=https://${GITEA_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_INFRA_RUNNER_TOKEN}
      - GITEA_RUNNER_LABELS=gitea-infra
    volumes:
      - ./data-runner:/data
      - ./data:/gitea-data
      - /var/run/docker.sock:/var/run/docker.sock

